@ECHO OFF

CALL SETVARIABLE DEV "C:\dev"
ECHO(
CALL SETVARIABLE SHORTCUTS "C:\Shortcuts"
ECHO(
CALL SETVARIABLE DROPBOX "%USERPROFILE%\Dropbox"
ECHO(
REM CALL SETVARIABLE SCREENSHOTS "%DROPBOX%\Screenshots"
REM ECHO(
REM CALL SETVARIABLE JIRAURL "https://company.atlassian.net"
REM ECHO(
REM CALL SETVARIABLE JIRAUSERNAME "firstname.lastname"
REM ECHO(
REM CALL SETVARIABLE COMPANY "Company"
REM ECHO(
REM CALL SETVARIABLE COMPANY2 "Company2"
REM ECHO(
REM CALL SETVARIABLE ORG "company"
REM ECHO(
REM CALL SETVARIABLE SERVICENOWURL "https://company.service-now.com"
REM ECHO(
REM CALL SETVARIABLE SERVICENOW2URL "https://companytest.service-now.com"
REM ECHO (
REM CALL SETVARIABLE PROXYURL "http://company.com/proxyfile.pac"
REM ECHO(
